name: 3D Profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          username: akashpk41
      - uses: actions/upload-artifact@v3
        with:
          name: profile-3d-contrib
          path: ./profile-3d-contrib
      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated 3D profile"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
